### ISSUE TITLE
Missing css on Bower.json 

### ISSUE THREAD

**Issue by clabnet** [blackat/ui-navbar#11]
I think you can add the .css into these files :

package.json, bower.json and dot bower.json

`"main": ["./release/js/ui-navbar.js", "./release/css/ui-navbar.css"],`

And re-sync the bower.json with dot bower.json, for windows user's.

Thank you for your work.

**Comment by blackat** [comment]
@clabnet file added in version 0.4.5.

Please reopen it if not fine.
