### ISSUE TITLE
about ui-router substate dot syntax

### ISSUE THREAD

**Issue by yuanshanxiaoni** [blackat/ui-navbar#13]
hi blackat,  thanks for your amazing module.

i have a question about using,  in my project,  

$scope.tree = [{
  state:'state',
  link:'state.html'
},
state: 'state.sub',
link: 'sub.html'
];

it's not worked in dot syntax of ui-router configuration.
.state('news.upcoming', {
            url:'upcoming',
            .... }

if i change my state config to parent syntax, it works well. 
.state('upcoming', {
            parent:'news',
            url:'upcoming' ..... }

it's that right ?

**Comment by blackat** [comment]
@poornigga sorry for late response but I was on holidays, could you please reproduce the issue in a plunkr?

**Comment by blackat** [comment]
@poornigga close the issue due to inactivity.
