### ISSUE TITLE
In mobile multi-level menu, tap on mid-level entry causes expand-collapse back-to-back

### ISSUE THREAD

**Issue by lrirwin** [blackat/ui-navbar#15]
Using Chrome on Android - tap the collapsed mobile menu on top-right, tap a "carat" icon parent menu entry, tap a mid-level menu entry and the sub-menu items expand and then immediately collapse making them inaccessible.
It is possible to access them, but you have to touch and hold until an options pop-up appears, then go "back" and tap the desired item...
It works fine when it isn't in the mobile mode...
Is it possible to make each level stay expanded until a valid link is activated or another tap collapses the list?

**Comment by lrirwin** [comment]
The pertinent items in use for this issue:
    link rel="stylesheet" href="css/bootstrap-3.3.6.min.css"
    link rel="stylesheet" href="css/ui-navbar-0.4.3.css"
    link rel="stylesheet" href="css/MaterialIcons.css"
    script src="js/angular-1.5.0-rc.2.min.js"
    script src="js/angular-messages1.5.0-rc.2.min.js"
    script src="js/angular-resource1.5.0-rc.2.min.js"
    script src="js/angular-route1.5.0-rc.2.min.js"
    script src="js/angular-animate1.5.0-rc.2.min.js"
    script src="js/angular-touch1.5.0-rc.2.min.js"
    script src="js/ui-bootstrap-tpls-1.3.2.min.js"
    script src="app/app.menutest.js"
    script src="js/ui-router-0.2.18.min.js"
    script src="js/ui-navbar-0.4.3.js"

**Comment by blackat** [comment]
Hi @lrirwin ,
thanks for you comment, well I have never tested on a mobile device so I should check what's going on and if a new lib should be loaded to manage the touch gesture.

What kind of mobile device are you using? I can test on an ipad or an iphone I do not have Android devices. Are you able to reproduce the issue even in Chrome with debug panel open and mobile mode activated?

Thanks for you attention :wink:

**Comment by lrirwin** [comment]
Hi Eugenio,

I'm testing it on a Samsung Galaxy Note 4 running Android 5.1.1 using 
Chrome 49.0.2623.105.
I'm also using Chromium 49.0.2623.108 on Ubuntu 14.04 (64-bit) for the 
desktop environment.

There also seems to be a different, but related, issue when you reduce 
the window size on a desktop instance of Chromium.
In that environment, you click the top level collapsed menu icon and it 
expands the navbar vertically.
If you click a top level level menu, it expands as well and the sub-menu 
remains visible.
All the rest of the sub-menu levels operate solely on the hover event.
You cannot click on a sub-menu header item and have the sub-submenu 
items remain visible.
Doing so collapses the submenu, returning you to the top level menu display.
These may both be the same issue, just exposing themselves in different 
manners due to the input methods.

It may be that this is intentional in your design.
I can see how it would be, but it puts in a switch the user must figure 
out in UI from the first levels to the following levels.

Thanks for all your work!
Larry Irwin

**Comment by blackat** [comment]
@lrirwin Sorry man but I have tried to get and Android phone to replicate the issue but no way, I have to close the issue. Please if you can investigate and find the issue you can do a pull request.

Have a nice day 😉
