### ISSUE TITLE
about navbar title by Json 

### ISSUE THREAD

**Issue by CaffreyChang** [blackat/ui-navbar#16]
Hello,
  I have some questions to need your help.If I want the navbar title still using by Json,is that possible?
If it can,can you teach me how does it use?
I hope the red square(
appendix) only appear once.And "Dropdown" &"Just a clone"(navbar title) data by Json.

appendix: http://imgur.com/2lKGl6R

Best Regards,
Caffrey

**Comment by blackat** [comment]
@CaffreyChang so the question is not really clear, as far as I got you want to set the title of the dropdown in the json file? for the time being is not possible, may be in the next release.
