### ISSUE TITLE
loading spinner

### ISSUE THREAD

**Issue by ghost** [blackat/ui-navbar#5]
Click a menu item, if it takes longer time to load the page, how to show a loading spinner?

**Comment by blackat** [comment]
Well, when you click on an item in the menu bar the corresponding state is loaded by the ui-router and it should not take more than one millisecond. If the page takes a lot to load means that you have one or more requests to the backend which take a significant amount of time.

The spinning wheel should be put in your page where you have the long request, so the page starts with a spinning wheel that disappears when the long requests ends, for instance:

`$http.get('api/items').then(function(response){
    // end of spinning wheel
}`

hope it helps.
