### ISSUE TITLE
Don't list dist/ui-navbar.js as main in package.json

### ISSUE THREAD

**Issue by tolmasky** [blackat/ui-navbar#6]
I may be mistaken, but it seems that package.json lists the main field as dist/ui-navbar, despite this file not existing. This confuses our systems into trying to require it when it shouldn't. Just removing this field should do the trick. Of course if I'm wrong and this should show up somehow my apologies.

**Comment by blackat** [comment]
Hi,
you are right, the main property had a wrong value, I have done the update.

Thanks :wink:
