### ISSUE TITLE
html dependancies

### ISSUE THREAD

**Issue by dbroadhurst** [blackat/ui-navbar#8]
I noticed the module has html dependancies in the module definition. I've not seen this done before and my unit test fails. I'm using ngbp as a project skeleton, anyone have a good way to allow this module to pass a unit test?

**Comment by blackat** [comment]
Hi,
I am not sure if I have correctly understood your question, basically you want to do some unit test, for instance with Jasmine, so you instantiate your module app in a beforeEach block and then you write unit test in a it block.

The trick is to load html templates modules you can find under template such as `navbar-li.html.js`. It is a normal (good?) practice separating the templates, in this case plain html code.

To load them you have just to load them as a normal JavaScript module
`beforeEach(module('uib/template/accordion/accordion.html'));`

If you open one of the JavaScript file wrapping the template you will see something like
`angular.module("template/navbar-li.html", [])` that is 
- create module with the name "template/navbar-li.html"
- run the module, means kickstart the module/application once the injector has done its work
- load the template into cache

Now you have your template inside of Angular Cache, the test should not fail.

You can find and example [here](https://github.com/angular-ui/bootstrap/blob/master/src/accordion/test/accordion.spec.js)

Hope it helps.

**Comment by blackat** [comment]
Since I have not got any update, I consider the issue solved. In case, please, reopen it :wink:
