### ISSUE TITLE
Dropdown doesn't work with "angular-ui-bootstrap > 1.0.3"

### ISSUE THREAD

**Issue by MileanCo** [blackat/ui-navbar#9]
The dropdown mechanism doesnt work with angular-ui-bootstrap version > 1.0.3.  

It needs to use these directives: https://angular-ui.github.io/bootstrap/#/dropdown

**Comment by lganet** [comment]
+1

**Comment by blackat** [comment]
Thanks for the issue, I will try to have a look at it asap :wink:

**Comment by blackat** [comment]
Hi folks!
I have not uploaded yet the project but it should be quite straightforward. 

I have modified the [plunkr example](http://plnkr.co/edit/zyxXk6w079OgswKHQgno), if I am not wrong it is enough to change the tags according to the [migration guide](https://github.com/angular-ui/bootstrap/wiki/Migration-guide-for-prefixes).

Please let me know if it works for you as well, then I will update the documentation and the demo project.

Tested with
- AngularJS 1.4.8
- Angular Animate 1.4.8
- UI-Bootstrap 1.1.0
- Twitter Bootstrap 3.3.6
- UI Router 0.2.15

**Comment by lganet** [comment]
Here, all rigth.

thanks.

**Comment by blackat** [comment]
Super, I close the issue and I will release a new version with the README.md updated.

Thanks for the feedback :wink:
